import express from 'express';
import fs from 'fs';
import path from 'path';
import archiver from 'archiver';

const router = express.Router();

router.get('/', (req, res) => {
  try {
    const { userId } = req.query;

    if (!userId) {
      return res.status(400).json({ error: 'UserId is required' });
    }

    const userDir = path.resolve(`generated/${userId}`);

    if (!fs.existsSync(userDir)) {
      return res.status(404).json({ error: 'No files to export' });
    }

    // Find the most recent system directory
    const dirs = fs.readdirSync(userDir, { withFileTypes: true })
      .filter(dirent => dirent.isDirectory() && dirent.name.endsWith('System'))
      .map(dirent => ({
        name: dirent.name,
        path: path.join(userDir, dirent.name),
        mtime: fs.statSync(path.join(userDir, dirent.name)).mtime
      }))
      .sort((a, b) => b.mtime - a.mtime);

    if (dirs.length === 0) {
      return res.status(404).json({ error: 'No files to export' });
    }

    const generatedDir = dirs[0].path;
    const systemName = dirs[0].name;

    // Set response headers for ZIP download
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename=${systemName}-${userId.slice(0, 8)}.zip`);

    // Create ZIP archive
    const archive = archiver('zip', { zlib: { level: 9 } });

    archive.on('error', (err) => {
      throw err;
    });

    archive.pipe(res);

    // Add README
    const readme = `# DataShark IA - ${systemName}

Generated on: ${new Date().toLocaleString()}
User ID: ${userId}

## Installation

1. Open Roblox Studio
2. Enable HTTP Requests in Game Settings → Security
3. Drag these scripts into ServerScriptService
4. Test your game!

## Files Included

${fs.readdirSync(generatedDir).filter(f => f.endsWith('.lua')).map(f => `- ${f}`).join('\n')}

---
Generated by DataShark IA
`;

    archive.append(readme, { name: 'README.md' });

    // Add all Lua files
    const files = fs.readdirSync(generatedDir);
    for (const file of files) {
      if (file.endsWith('.lua')) {
        const filePath = path.join(generatedDir, file);
        const content = fs.readFileSync(filePath, 'utf8');
        archive.append(content, { name: file });
      }
    }

    archive.finalize();
  } catch (error) {
    console.error('Export error:', error);
    res.status(500).json({ error: error.message });
  }
});

export default router;
